edition = "0.4.0"
target_files = []

[metadata_remote]
type = "S3"
base_dir = ""
url = "https://gateway.storjshare.io"
require_credentials = true
username = ""
password = ""
access_key = ""
secret_key = ""
bucket_name = ""
bucket_region = ""

[file_remote]
type = "S3"
base_dir = ""
url = "https://gateway.storjshare.io"
require_credentials = false
username = ""
password = ""
access_key = ""
secret_key = ""
bucket_name = ""
bucket_region = ""

[[source_files]]
key = "readme"
local_path = "./README.md"
target_filename = "README.md"
target_directory = "./"
