name = ""
edition = "0.5.7"
version = "0.0.0"
target_files = []

[metadata_remote]
type = ""
base_dir = ""
url = ""
username = ""
password = ""
access_key = ""
secret_key = ""
bucket_name = ""
bucket_region = ""
require_credentials = true
ignore_version = false
ignore_checksum = false

[file_remote]
type = ""
base_dir = ""
url = ""
username = ""
password = ""
access_key = ""
secret_key = ""
bucket_name = ""
bucket_region = ""
require_credentials = true
ignore_version = true
ignore_checksum = true

[[source_files]]
key = "readme"
local_path = "./README.md"
target_filename = "README.md"
target_directory = "./"
